### ISSUE TITLE
Onnx Assertion Error

### ISSUE THREAD

**Issue by sanarberkebayram01** [Unity-Technologies/barracuda-release#247]
There is a problem when i try to take inference from the [model](https://github.com/Kazuhito00/AnimeGANv2-ONNX-Sample/blob/main/model/face_paint_512_v2_0.onnx)

I can clearly use onnx on pytorch and onnxruntime in python. 
Given assertion Error
`UnityEngine.Assertions.AssertionException: Assertion failure. Values are not equal.
Expected: 32 == 1`

**Comment by AlexRibard** [comment]
thank you for providing the model, we will take a look a it

**Comment by sanarberkebayram01** [comment]
Any progress ?

**Comment by AlexRibard** [comment]
Yes, there was a few issues with our importer that I fixed. (changes are a bit too big to share on github). 
But they will make it for the next release.

One side note is about this pattern
![image](https://user-images.githubusercontent.com/12990800/148811398-e3350685-86e2-4eef-9987-b5662876b8ae.png)
This is extremely costly and our current kernels will not work for such a large input size.
I'd suggest to re-import the model with a smaller size

let me know

(closing the issue as the problem has been fixed, but feel free to respond in the chat)

**Comment by TUANANH-INU** [comment]
Hi AlexRibard ! 
I am also working on a similar project and encountered the above error, do not know if barracuda has an updated version for this error so far.

`UnityEngine.Assertions.AssertionException: Assertion failure. Values are not equal. Expected: 32 == 1`

Currently I am using barracuda version 3.0 - March 01, 2022. But this error still appears.

Thanks.
