### ISSUE TITLE
8D shape of input and output tensor 

### ISSUE THREAD

**Issue by chinmaychinara91** [Unity-Technologies/barracuda-release#96]
Hi Barracuda Team,

Barracuda version: 1.1.2 (preview)
Opset version: 9
Pytorch: 1.3

When I load my model into Unity I see the shape of the tensors of input and output to be 8D even though it's actually 4D while creating the onnx from Pytorch. Even though the model works fine but still why this weird behavior.

![Capture](https://user-images.githubusercontent.com/21283733/96187695-4c4e3380-0ef2-11eb-8f30-7300779855ea.PNG)

In the attachment above:
Input should be: [B,H,W,C]->[1,224,224,3]
Output should be: [B,H,W,C]->[1,1,1,512]

This happened specifically after I updated my Unity barracuda from 1.0.3 to 1.1.2(preview)

**Comment by AlexRibard** [comment]
Hi! Yes indeed. As part of 1.1.2 we now support 8D tensors for a number of models.
UI/Documentation has not been properly updated to explain this. 
I agree this is confusing. UI will be updated it in the next release to properly reflect input dimensions

**Comment by chinmaychinara91** [comment]
> Hi! Yes indeed. As part of 1.1.2 we now support 8D tensors for a number of models.
> UI/Documentation has not been properly updated to explain this.
> I agree this is confusing. UI will be updated it in the next release to properly reflect input dimensions

@AlexRibard that's amazing. I felt it could be that but could not find documentation for it. Thanks a lot.

**Comment by chinmaychinara91** [comment]
@AlexRibard I still think 1.1.2 (preview) does not support the >4D tensor because I have an onnx model which has the shape [1, 60, 224, 224, 3] but still it gives the error of rank.

Stack Trace:

**Asset import failed, "Assets/Resources/Models/cnn_1_60_224_224_3.onnx" > OnnxLayerImportException: Only tensors of rank 4 or less are supported, but got rank 5**
Unity.Barracuda.ONNX.ONNXLayout.AxisPermutationsForMappingONNXLayoutToBarracuda (System.Int32 onnxRank, System.String onnxLayout) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXLayout.cs:45)
Unity.Barracuda.ONNX.ONNXLayout.PermuteToBarracuda (System.Int64[] shape, System.String onnxLayout, System.Int32 defaultValue) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXLayout.cs:159)
Unity.Barracuda.ONNX.ONNXLayout.ConvertSymbolicShapeToBarracuda (System.Int64[] onnxShape, System.String onnxLayout) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXLayout.cs:224)
Unity.Barracuda.ONNX.ONNXLayout.ConvertSymbolicShapeToBarracuda (Onnx.TensorShapeProto shape, System.String onnxLayout) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXLayout.cs:219)
Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:1170)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:82)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:60)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Editor/ONNXModelImporter.cs:44)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <90d4bcb003fb405fb09241aed2f178aa>:0)
UnityEditor.Experimental.AssetImporters.AssetImporterEditor:ApplyRevertGUI()
Unity.Barracuda.ONNXModelImporterEditor:OnInspectorGUI() (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Editor/ONNXModelImporterEditor.cs:41)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

UnityEditor.Experimental.AssetImporters.AssetImporterEditor:ApplyRevertGUI()
Unity.Barracuda.ONNXModelImporterEditor:OnInspectorGUI() (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Editor/ONNXModelImporterEditor.cs:41)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Attached is the model.
[https://drive.google.com/file/d/1hMlkPUDq6tD7wQfMDcStehcs9wjMoUYl/view?usp=sharing](url)

**Comment by FlorentGuinier** [comment]
Hi @chinmaychinara91 
Indeed in 1.1.2 8D basic support was added at operators and tensors level (aka Barracuda runtime) however, as you have noticed, the ONNX import process mostly require 4D still. Barracuda 1.2.0 (currently in the process of being released) is building on this and expand ONNX import to support >4D in more use cases (with a special focus on shufflenet,superresolutioncnn,yolov3 and tinyyolov3). The error above being fixed in revision 1.2.0.

Looking at the model attached above however you will still have trouble importing, the network contain a very large number of nodes and fail on importing with a "IO Exception: stream too long" exception, I will look into that however in order to run in 1.2.0 (and for the sake of runtime performance) a would advice a smaller network if possible for the problem. Let us know if that is possible :) ?

PS : I will keep you posted on the `IO Exception: stream too long` problem here.

**Comment by FlorentGuinier** [comment]
Update on `IO Exception: stream too long` -> On 1.2.0 network import fine the 15841 nodes, however because of legacy reason (aka before in Editor ONNX importer) we serialize the model to disk as a single binary file after importing. That last step fail because we serialize all layer weights unshared leading to an overflow in System.IO.MemoryStream.Write (write index is int and overflow). This is fixable however I'm not sure it is worth it as the network performance and memory consumption with that amount of nodes will be really bad.

Summary :
5D Import problem --> fixed in 1.2.0
Large amount of node/weight lead to overflow when serializing --> Will not fixed as runtime performance won't be worthy.

Please feel free to reopen if you feel i'm missing something or want to speak more about it!

Have a great day.

Florent

**Comment by chinmaychinara91** [comment]
@FlorentGuinier Thank you for the detailed explanation. So for this issue of 5D tensors and large model size, I have a further optimized version of the model which definitely is faster and is runtime efficient. It's now a 3 input LSTM classification network. However, it still throws some error which I am in discussion with @AlexRibard in a separate thread https://github.com/Unity-Technologies/barracuda-release/issues/95. We can consider this issue closed and let's take the discussion there.
